[package]
name = "sdrapp-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sdrapp-core = { path = "../sdrapp-core" }
sdrapp-adsb = { path = "../sdrapp-adsb" }
sdrapp-orbcomm = { path = "../sdrapp-orbcomm" }
sdrapp-tle = { path = "../sdrapp-tle" }
num-complex = { workspace = true }
sdrapp-midi = { path = "../sdrapp-midi" }
sdrapp-recorder = { path = "../sdrapp-recorder" }
egui = { workspace = true }
eframe = { workspace = true }
egui_plot = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
crossbeam-channel = { workspace = true }
dirs = { workspace = true }
serde_json = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }
ureq = { version = "2", features = ["tls"] }
open = "5"
