[package]
name = "sdrapp-orbcomm"
description = "Orbcomm SDPSK demodulator and packet parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
num-complex = { workspace = true }

[dev-dependencies]
approx = "0.5"
